### PR TITLE
add from/into implementations for std::mspc errors

### LINKED ISSUE #34: add into() implementation for std::sync::mpsc::TrySendError
## Use Case

I would like for the [`ch!`](https://docs.rs/ergo_sync/0.1.0/ergo_sync/macro.ch.html) macro to be able to move to it's own crate and be usable for _any_ current or future non-blocking channel. ~~I think this would allow it to be usable by a `futures-channel` crate even (maybe with a bit of added syntax for the `Context` argument).~~ (meh, that isn't really known)

## Feature request

Add `into()` to convert to the stdlib type, or use the stdlib type directly.

## Reasoning

As far as I can tell these types are basically identical

-  [std::sync::mpsc::TrySendError](https://doc.rust-lang.org/std/sync/mpsc/enum.TrySendError.html)
```
pub enum TrySendError<T> {
    Full(T),
    Disconnected(T),
}
```

[crossbeam_channel::TrySendError](https://docs.rs/crossbeam-channel/0.1.2/crossbeam_channel/enum.TrySendError.html)
```
pub enum TrySendError<T> {
    Full(T),
    Disconnected(T),
}
```

The same is true for TryRecvErorr (from std):
```
pub enum TryRecvError {
    Empty,
    Disconnected,
}
```

### PR DESCRIPTION
**Pull request by vitiral**
fixes #34 

It ended up being that I _did_ have to define both. `From<mpsc::*Error>` implemented `crossbeam_channel::*Error::Into<mpsc::*Error>` but not `mpsc::*Error::Into<crossbeam_channel::*Error`

### CODE REVIEW

**Comment by vitiral** [comment]
hmm... it's possible I don't need the second one though. Just a sec.

**Comment by vitiral** [comment]
nevermind, this implementation is correct. You need `impl Into<mpsc::TryRecvError> for TryRecvError`

**Comment by stjepang** [comment]
Looks good. Before merging, let's also add conversions for `SendError`, `RecvError`, and `RecvTimeoutError`. :)

**Comment by vitiral** [comment]
You want conversions to their `std::sync` variants right?

**Comment by stjepang** [comment]
Yes - since we're adding conversions for `TrySendError` and `TryRecvError`, why not go all the way and do the same for the other three error types.

**Comment by vitiral** [comment]
sounds good, will do.

**Comment by stjepang** [comment]
I've added conversion methods `SendError`, `RecvError`, and `RecvTimeoutError`.

**Comment by stjepang** [comment]
After #41 gets merged, we won't have error types anymore. Closing.

**Pull request closed without merging**
