### PR TITLE
Select struct for dynamic lists of cases

### LINKED ISSUE #63: Select over multiple receivers with different types
I'm writing a small library to aggregate and report different types of events to a collection server.

In crossbeam-channel 0.2.1 I could store receivers of different message types in one collection:

```rust
trait ErasedChannel: Send {
    fn recv(&mut self, select: &mut Select) -> Result<(), SelectRecvError>;
}

struct Channel<V> {
    rx: Receiver<V>,
    reporter: Report<V>,
}

impl<V> ErasedChannel for Channel<V>
where
    V: Send,
{
    fn recv(&mut self, select: &mut Select) -> Result<(), SelectRecvError> {
        let msg = select.recv(&self.rx)?;
        self.reporter.report(msg);
        Ok(())
    }
}

pub struct Collector {
    channels: Vec<Box<ErasedChannel>>,
}

impl Collector {
    fn aggregate(&mut self, deadline: Instant) {
        'aggregating: loop {
            // Convert deadline into duration for select's timeout
            let timeout = match Instant::now() {
                x if x < deadline => deadline - x,
                _ => break 'aggregating,
            };

            let mut select = Select::with_timeout(timeout);

            'selecting: loop {
                for mut channel in &mut self.channels {
                    if let Ok(_) = channel.recv(&mut select) {
                        break 'selecting;
                    }
                }

                if select.timed_out() {
                    break 'selecting;
                }
            }
        }
    }
}
```

Is it possible to achieve something similar with crossbeam-channel 0.3?

### PR DESCRIPTION
**Pull request by stjepang**
The new `Select` struct allows one to declare cases in a select dynamically, in contrast to enumerating all of them statically inside a `select!` macro.

`Select` follows a builder-like pattern: it is constructed using `new()`, we add cases using `recv()`, `send()`, and `default()`, and finally call `wait()` to start selection. The overall syntax is reminiscent of `select!`.

For example, these two selects are equivalent:

```rust
select! {
    recv(r1, v) => assert!(v.is_none()),
    recv(r2) => panic!(),
    default => panic!(),
}
```

```rust
Select::new()
    .recv(&r1, |v| assert!(v.is_none()))
    .recv(&r2, |_| panic!())
    .default(|| panic!())
    .wait();
```

cc @tecywiz121 @matklad - What do you think, would this interface work for you? Would you like anything to be done differently?

I need your help to nail down a few details:

1. Should `wait` be called `run` or `start`, or maybe something else?
2. Should `wait` take `Select` as `&mut self` or as `self`?
3. If we go with `&mut self`, what should happen if `.wait()` is called twice? Maybe panic? Note that we cannot reuse a single instance of `Select` for multiple invocations because the closures are of type `FnOnce`.

One drawback of `Select` is that it appears to be 2x slower than `select!`, which is probably due to all those closure shenanigans. However, if performance is of concern, the overhead is relatively easy to optimize away: I suggest manually attempting non-blocking receive/send operations and falling back to selection only when none of the operations are ready.

Closes #63

### CODE REVIEW

**Comment by matklad** [comment]
I think this'll work for me, yeah. I might try this branch out, and leave a feedback if/when I do.

Cursory comments:

1) it might be interesting to use `FnOnce(Option<T>) -> R` for callbacks and `-> R` for wait, to express the guarantee that at lest one callback is invoked in `wait`.
2) it's interesting that currently it's impossible to simulate the first API by making a `Option<R>` slot and assigning to it from a callback, because you can't close over `&mut` by several closures simultaneously. So, for the full generality, I think `Select` should accept a `Ctx` in its `new` method and provide this `Ctx` to callbacks. 
3) for my use-case, a statically-dispatched version of this (where `Select` is parametrized by callback and previous select) would work as well. 

It's also fun that I have a [similarlish visitor API](https://github.com/matklad/libsyntax2/blob/971054e4d026a4d39dc6229ba8883bef626b11e3/crates/libsyntax2/src/algo/visit.rs#L23-L34) which does 1) (return types), 2) (explicit closure capture) and 3) (static dispatch) in libsyntax :)

**Comment by stjepang** [comment]
Thanks for the feedback!

1. This is a good idea, I've just pushed a new commit that does as suggested.

2. `RefCell` would work here. :) Just to clarify, are you suggesting to parametrize `Select` over `Ctx` as in `Select<'a, Ctx, R>`?

3. Oh, so you mean something like `Select<'a, F1, Select<'b, F2, Select<'c, F3, None>>>`? I like that idea, but worry that this would make it impossible to register an arbitrary list of receivers like `Vec<Receiver<()>>` (unless we add a new method - something like `fn recv_iter<T, C>(&mut self, impl IntoIterator<Receiver<T>>, cb: C)`).

**Comment by matklad** [comment]
2) yes, RefCell would work, and yes, alternatively we can add `Ctx` as a type-parameter to `Select`. I'd say `RefCell` is a decent-enough workaround.
3) yes, that telescopic type is what I have in mind. I think it *can* work for dynamic case if we also add a Select trait which is object-safe (sort-of how `Iterator` works). Again, this is an option, not something I actually suggest doing :) Though, I think it might be fun to recast `select!` macro implementation in terms of such telescopic type, if possible (hm, and that won't be possible precisely because of `&mut` captures across closures TT ).

**Comment by tecywiz121** [comment]
Gave it a quick lookover, and it looks perfect for my usecase. Thanks!

**Comment by stjepang** [comment]
Ok, this PR is ready now. I'll leave it for a few days so everyone can take a look at it. Let me know if you have any comments or concerns!

To see the docs and the interface, go here: https://github.com/crossbeam-rs/crossbeam-channel/blob/e0c698f87dfbb339d73aaa9197b75de123980e44/src/internal/select.rs#L314

@BurntSushi If you're interested: This is the equivalent of [`reflect.Select`](https://golang.org/pkg/reflect/#Select) in Go, except it uses a builder-like pattern that fits Rust better, I think.

**Comment by BurntSushi** [comment]
@stjepang Wow! This is awesome!

**Comment by stjepang** [comment]
This is now published in version 0.2.6:

https://docs.rs/crossbeam-channel/0.2.6/crossbeam_channel/struct.Select.html

**Pull request merged**
